


version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - export SONAR_SCANNER_VERSION=5.0.1.3006
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - export SONAR_SCANNER_OPTS="-server"
  build:
    commands:
      - set -e
      - sonar-scanner -X -Dsonar.login=407551ac073f15203772206cd489508da68fee8d -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=Vacation-memories -Dsonar.organization=vinay23107 -DgeneratePom=true
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=hotel >result.json
      - cat result.json
    
